language: swift
xcode_sdk: iphonesimulator13.7
osx_image: xcode11.6
git:
  submodules: false
jobs:
  include:
    - name: "SPM Build"
      script:
        - set -o pipefail
        - swift build
    - name "Carthage Build"
      before_script:
        - carthage bootstrap
      script:
        - set -o pipefail
        - carthage build --no-skip-current
before_install:
    - brew update
    - brew outdated carthage || brew updagrade carthage
notifications:
  email:
    on_success: never
