language: swift
xcode_sdk: iphonesimulator13.7
osx_image: xcode11.6
env:
  global:
    - PROJECT=CTXTutorialEngine.xcodeproj
git:
  submodules: false
matrix:
  include:
    - env: JOB="LINUX_SPM" SWIFT_VERSION="5.0"
      sudo: required
      dist: trustly
      script:
        - swift build
    - env: JOB="XCODE" DEST="OS=11.0,name=iPhone6" SCHEME="CTXTutorialEngine" SDK="iphonesimulator" ACTION="test" PLATFORM="iOS"
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
script:
  - set -o pipefail
  - xcodebuild "$ACTION" -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DEST" -configuration Release | xcpretty
notifications:
  email:
    on_success: never
