language: swift
xcode_sdk: iphonesimulator13.7
osx_image: xcode11.6
xcode_project: CTXTutorialEngine.xcodeproj
xcode_scheme: CTXTutorialEngine
git:
  submodules: false
jobs:
  include:
    - name: "SPM Build"
      script:
        - set -o pipefail
        - swift build
    - name: "Carthage Build"
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      script:
        - set -o pipefail
        - carthage build --no-skip-current
notifications:
  email:
    on_success: never
